on:
  workflow_call:
    inputs:
      docker_file:
        type: string
        required: true
      docker_context:
        type: string
        required: true
      namespace:
        type: string
        required: true
      app_name:
        type: string
        required: true
      rollout:
        type: string
        required: false
        default: 'false'
    secrets:
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true
      AZURE_KUBERNETES:
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Get current datestamp
        id: datestamp
        shell: bash
        run: echo "::set-output name=datestamp::$(date '+%G%m%d%H%M%s')"

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.ACR_USERNAME }} 
          password: ${{ secrets.ACR_PASSWORD }}
          login-server: https://elfsquad.azurecr.io

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ inputs.app_name }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.docker_context }}
          file: ${{ inputs.docker_file }}
          push: true
          tags: elfsquad.azurecr.io/${{ inputs.app_name }}:${{ inputs.namespace }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_KUBERNETES }}
          cluster-name: kube-we-1
          resource-group: Elfsquad
      
      - run: kubectl rollout restart deployment ${{ inputs.app_name }}-deployment -n ${{ inputs.namespace }}
        if: ${{ inputs.rollout == 'true' }}
        shell: bash
